{
"name": "Gift Product Configurator",
"version": "18.01.08",
"summary": "Advanced B2B product page for promotional gifts",
"category": "Website",
"author": "SelectAd",
'license': 'LGPL-3',
"depends": [
   'product',
   'website',
   'website_sale',
   'sale_management'
],
"data": [
    "views/product_page.xml",
    'views/bestsellers_page.xml',
    'views/shop_category_hero.xml',
    'views/product_public_category_form.xml',
    'data/sequence.xml',
    'views/quote_drawer_template.xml',
    "views/quote_scripts.xml",
    "views/larger_quantity_template.xml",
    'views/vendor_import_job_views.xml',
    'data/cron.xml',
    'views/res_partner_view.xml',
    'views/portal_vendor_button.xml',
    'security/security.xml',
    'security/product_vendor_rule.xml',
    'security/ir.model.access.csv',
    'views/product_template_views.xml',
    'views/product_mass_update_views.xml',
],
"assets": {
    "web.assets_frontend": [
        "gift_product_configurator/static/src/scss/product_page.scss",
        "gift_product_configurator/static/src/scss/bestsellers.scss",
        "gift_product_configurator/static/src/scss/quote_drawer.scss",
        "gift_product_configurator/static/src/scss/shop_hero.scss",
        "gift_product_configurator/static/src/scss/category_hero.scss",
        #"gift_product_configurator/static/src/scss/variants.scss",
        "gift_product_configurator/static/src/scss/larger_quantity.scss",
        "gift_product_configurator/static/src/scss/vendor_tool.scss",
        "gift_product_configurator/static/src/scss/portal.scss",
        "gift_product_configurator/static/src/js/configurator.js",
    ],
},
 'installable': True,
 # ✅ CUSTOM FIELD
#'pre_init_hook': 'add_vendor_column',
}

