{
    "name": "Gifting Theme",
    "version": "18.0.1.0.0",
    "category": "Theme/Corporate",
    "depends": [
        "website", 
        "product", 
        "sale",
        "website_sale",
        "sale_management",
        "payment",
        "website_sale_wishlist", 
    ],
    "data": [
        'views/layout.xml',
        #'views/theme.xml',
        "views/header.xml",
        "views/hero.xml",
        'views/category_card.xml',
        'data/product_categories.xml',
    ],
    "assets": {
        "web.assets_frontend": [
            "theme_gifting/static/src/css/header.scss",
            "theme_gifting/static/src/css/hero.scss",
            "theme_gifting/static/src/css/product.scss",
            "theme_gifting/static/src/css/category_product.scss",
            'theme_gifting/static/src/css/gifting_sections.scss',
            "theme_gifting/static/src/js/cart_count.js",
            "theme_gifting/static/src/js/header.js",
            "theme_gifting/static/src/js/gifting.js",
        ],
    },
    "theme": True,
    "installable": True,
}
