{
    "name": "Gifting Theme",
    "version": "18.0.1.0.0",
    "category": "Theme/Corporate",
    "depends": [
        "website", 
        "product", 
        "sale",
        "website_sale",
        "sale_management",
        "payment",
        "website_sale_wishlist", 
    ],
    "data": [
        'views/layout.xml',
        #'views/theme.xml',
        "views/header.xml",
        "views/hero.xml",
        'views/product_card.xml',
        'views/section_cta_banner.xml',
        'views/section_main_category.xml',
        'views/section_new_arrivals.xml',
        'views/components/product_card_promo.xml',
        'views/section_promotions.xml',
        'views/section_faq.xml',
        'views/section_newsletter.xml',
        "views/section_popular_picks.xml",
        "views/section_popular_categories.xml",
        "views/section_promotional_products.xml",
        "views/section_testimonials.xml",
        "views/section_company_logos.xml",
        'views/category_card.xml',
        'data/product_categories.xml',
        #"views/promo_category_page.xml",
        "views/section_promotional_products.xml",
        "views/footer_custom.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "theme_gifting/static/src/css/header.scss",
            "theme_gifting/static/src/css/main.scss",
            "theme_gifting/static/src/css/hero.scss",
            "theme_gifting/static/src/css/product.scss",
            "theme_gifting/static/src/css/category_product.scss",
            'theme_gifting/static/src/css/gifting_sections.scss',
            'theme_gifting/static/src/css/company_logos.scss',
            'theme_gifting/static/src/css/footer.scss',
            #'theme_gifting/static/src/css/promo_categories.scss',
            "theme_gifting/static/src/js/cart_count.js",
            "theme_gifting/static/src/js/header.js",
            "theme_gifting/static/src/js/gifting.js",
        ],
    },
    "theme": True,
    "installable": True,
}
