{
    "name": "ATK Navy Theme",
    "version": "18.0.1.0.0",
    "category": "Theme/Corporate",
    "depends": [
        "website", 
        "product", 
        "sale", 
        "website_sale",
    ],
    "data": [
        'views/layout.xml',
        'views/navbar.xml',
        'views/homepage.xml',
        'views/atk_about_page.xml',
        'views/pagetemplate.xml',
        'views/atk_booking_page.xml',
        'data/atk_products.xml',
        'data/atk_skipdline_products.xml',
        'views/global_modals.xml',
        'views/remove_branding.xml', 
    ],
    'assets': {
        'web.assets_frontend': [
            'theme_atk_navy/static/src/scss/atk_theme.scss',
            'theme_atk_navy/static/src/scss/atk_countdown.scss',
            'theme_atk_navy/static/src/scss/navbar.scss',
            'theme_atk_navy/static/src/scss/components/_buttons.scss',
            'theme_atk_navy/static/src/scss/booking_modal.scss',
            'theme_atk_navy/static/src/scss/appointment_figma.scss',
            'theme_atk_navy/static/src/scss/vehicle_modal.scss',
            'theme_atk_navy/static/src/scss/vehicle_modal_main.scss',
            'theme_atk_navy/static/src/scss/vehicle_dependent.scss',
            'theme_atk_navy/static/src/js/main.js',
            'theme_atk_navy/static/src/js/atk_countdown.js',
            'theme_atk_navy/static/src/js/atk_navbar.js',
            'theme_atk_navy/static/src/js/booking_modal_toggle.js',
            'theme_atk_navy/static/src/js/booking_modal.js',
            'theme_atk_navy/static/src/js/vehicle_modal.js',
            'theme_atk_navy/static/src/js/vehicle_data.js',
            'theme_atk_navy/static/src/js/vehicle_data_transponder.js',
            'theme_atk_navy/static/src/js/vehicle_skip-line_embed.js',
        ],
    },
    "theme": True,
    "installable": True,
}
